### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by rayanakiki** [adsau59/supbot#3]
Hello, can u please describe more how to install and run? Thanks

**Comment by adam-saudagar** [comment]
Github readme is outdated, sorry for that, refer this video for setting supbot
https://www.youtube.com/watch?v=XURtoZfKdBg&index=4&list=PLdeajH45r2EKfD4lB6LJW6jF66PLSFGFa

if you still have problem, let me know

Edit: thanks for reminding me, I have updated the readme too.

**Comment by adam-saudagar** [comment]
U haven't replied in 4 days, I am closing this issue, if u still get any problems, please open another issue or reply here I'll reopen the issue
