### ISSUE TITLE
supbot as yowsup substitution / CheckerActionThread crashing cuz of group without group prefix

### ISSUE THREAD

**Issue by nitoniso** [adsau59/supbot#4]
Can I use supbot as a substitution of alternative to yowsup for WhatsApp on integrating WhatsApp services on my web application. Please help

**Comment by adam-saudagar** [comment]
I havent used yowsup before, so I don't know, but can you explain what application you intent to build?

**Comment by nitoniso** [comment]
I am developing an online social media application. Users should be able to
post images and messages from their whatsapp account and also send images
and messages from the web application to their whatsapp contacts

**Comment by nitoniso** [comment]
Non of the comands is returning anythi g to the sender(group member)

**Comment by adam-saudagar** [comment]
You could build the system to post images and messages from whatsapp account to web application and vice versa, but right now supbot only works for groups not for personal chat. (and by using the whatsapp web method u can't really send message directly to someone, there will always be the bot in the middle)

**Comment by adam-saudagar** [comment]
U might not have added your group in Supbot use this command in the console, 
```
group add groupid
```
Where groupid is the unique id of the group written in the end of the group title like ```group name ;;groupid```

Watch the setup video, I have explained in there how to setup Supbot for development

**Comment by nitoniso** [comment]
i followed the whole procedure but its not showing anything. the code is
executing with an error though. Please see attached pictures.

**Comment by adam-saudagar** [comment]
I don't see any attached pictures

**Comment by nitoniso** [comment]
![screenshot_20180715-130836 1](https://user-images.githubusercontent.com/41240441/42741267-f2846b68-88b0-11e8-89ec-3831f024fd46.png)
![supbot](https://user-images.githubusercontent.com/41240441/42741268-f30619ec-88b0-11e8-829d-a022206952db.PNG)


attached the images.

**Comment by adam-saudagar** [comment]
oh looks like you are getting an exception, I am not able to replicate the exception you are getting

can you explain how to replicate the exception you are getting so that I can debug it?

**Comment by adam-saudagar** [comment]
okay I found the way to replicate it, it happens when a message comes to a group which doesnt have ";;" thing even if it is not added to the group, I'll fix it and commit it soon

thanks for creating the issue

**Comment by adam-saudagar** [comment]
so I fixed the bug, now it should work, just pull the latest commit, thanks for creating the issue, please create another issue if u find another bug.

**Comment by nitoniso** [comment]
Ohh great i will be very grateful. Looking forward for the fix

**Comment by nitoniso** [comment]
Hi Adam, I am having and error on trying to run the bot for the first time
and it is as follows,

Exception in thread "main" java.lang.NoClassDefFoundError:
org/openqa/selenium/WebDriver
    at supbot/in.definex.Main.main(Main.java:12)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.WebDriver

**Comment by adam-saudagar** [comment]
I think you haven't imported the jar files, try following this [video video tutorial](https://youtu.be/XURtoZfKdBg) to set up the development environment for supbot

**Comment by nitoniso** [comment]
I just solved the problem now. I marked th src folder as "sources root"
