### ISSUE TITLE
Cannot add bot to new group

### ISSUE THREAD

**Issue by meidikawardana** [adsau59/supbot#5]
Hi, please help. After I create new group, I cannot add bot to the new group. 
my machine is:
a. asus x450jf, windows 10, 64bit.
b. intellij 2018.2
c. jdk 1.8

the steps:
1. I watch https://www.youtube.com/watch?v=XURtoZfKdBg
2. I follow the video, all is well until before I ran project for first time (https://youtu.be/XURtoZfKdBg?t=208)
3. error appearing, like below:
![image](https://user-images.githubusercontent.com/2024380/46647081-43665100-cbb8-11e8-98c5-4f4e2e15f309.png)
error detail:

https://gist.github.com/meidikawardana/d3c833e391cce257a86a86c10eb0079f

4. I fixed that error, by adding to Run -> Edit Configurations -> VM Options, this line:
`-Dwebdriver.chrome.driver="D:\\wascrapper\\chromedriver.exe"`
it is the location of chromedriver in my harddisk
snapshot:
![image](https://user-images.githubusercontent.com/2024380/46648701-6d237600-cbc0-11e8-887d-9cc3042bd419.png)

5. after click Apply, OK, then I run project again. this time no error and all is well. I created new group like below:
![image](https://user-images.githubusercontent.com/2024380/46648774-bf649700-cbc0-11e8-80d8-da3d43c0b089.png)

6. and I add the group with command: `add group 3`
7. after that, I tried to command: `;;help` but the bot not react or anything. please help me..

**Comment by adam-saudagar** [comment]
Please make sure you have not clicked anything or done anything manually in whatsapp web

If you do it, it desyncs the information with Supbot.

**Comment by meidikawardana** [comment]
thanks for your response.. I just created new group via my phone, and I dont touch whatsapp web. I named the group: dana_titip;;4. 
then I add it: `group add 4` .
then I type on my phone (whatsapp): ;;help
but nothing happened.
maybe it will help you to trace if you try these:
1. download supbot latest zip from this github
2. update to latest whatsapp on android
3. update to latest google chrome on laptop
4. update to latest intellij
5. using latest chromedriver for windows
6. using jdk 1.8
7. then try to run it.

**Comment by adam-saudagar** [comment]
Okay let me check, maybe the xpath have changed

**Comment by meidikawardana** [comment]
thank you. you are the best. very fast response

**Comment by adam-saudagar** [comment]
xpaths are up to date, by the [image u uploaded](https://user-images.githubusercontent.com/2024380/46648774-bf649700-cbc0-11e8-80d8-da3d43c0b089.png) I can see that you are sending commands with the bot account, it doesnt work like that, you will have to use a secondary account to send commands to the bot

**Comment by meidikawardana** [comment]
my problem is gone. I will continue to your next video on youtube. thank you 👍
