### ISSUE TITLE
already registered, but cannot add-feature Math

### ISSUE THREAD

**Issue by meidikawardana** [adsau59/supbot#6]
hi, I have new problem. I tried to `add-feature Math` , but the bot said I dont have sufficient permission. please help.

![image](https://user-images.githubusercontent.com/2024380/46709555-79fea300-cc6e-11e8-8f47-d209119d08db.png)

I already replaced supbot.jar with the one at https://github.com/adsau59/supbot/blob/master/build/supbot.jar?raw=true .

**Comment by adam-saudagar** [comment]
You need admin or Co admin role in order to add feature to the bot you can either increase your role by runing this command in console 
```
run <groupid> promote <client-name>
```
in your case client-name will be "Meidika Wardana", run the above command till you have Admin role

or you can direct add the feature from the console command too using,
```
run <groupid> add-feature <feature-name>
```

**Comment by meidikawardana** [comment]
ok, adam. I will try it. if the issue resolved I will immediately close this issue. thanks for your info. 

I think you should update your video or write info about this somewhere. about this "promote" feature

**Comment by adam-saudagar** [comment]
sure np, I was think about creating a faq page

**Comment by meidikawardana** [comment]
hi adam. finally I understand, the problem with Math feature. in latest supbot.jar you provide, there is no Math Feature. I resolved this issue by creating a new jar myself, containing Math Feature & its command (solve). thanks for your help. cheers

**Comment by adam-saudagar** [comment]
oh yes, math feature wasn't a part of core features, so I removed it
