### ISSUE TITLE
Get error after run

### ISSUE THREAD

**Issue by frozenade** [adsau59/supbot#7]
I got these errors in Console.java while running Main:
```
Error:(9, 48) java: package com.sun.org.apache.xalan.internal.lib is not visible
  (package com.sun.org.apache.xalan.internal.lib is declared in module java.xml, which does not export it)
Error:(9, 1) java: static import only from classes and interfaces
```

Please help

**Comment by adam-saudagar** [comment]
Did u include all the external libraries? Follow the setup tutorial [link](https://youtu.be/XURtoZfKdBg)

**Comment by frozenade** [comment]
Yes, I did. But still no luck. I got stuck after minute 3:30 on video.

**Comment by adam-saudagar** [comment]
Alright I'll check it out, but ull have to wait couple of days.

**Comment by frozenade** [comment]
Thanks in advance. FYI, I installed all required software, fresh. I just wondering what does `package com.sun.org.apache.xalan.internal.lib` mean.

**Comment by adam-saudagar** [comment]
I think there is a problem with your java environment...
can u tell me what java version and IDE u are using?

and can u send me a screenshot along with the error?

**Comment by frozenade** [comment]
I use latest Java 11 and latest IntelliJ IDEA.
I'll catch the screen at a moment.

**Comment by adam-saudagar** [comment]
Can u try installing java 8?

Supbot API uses java 8 that might be the problem

**Comment by adam-saudagar** [comment]
Have u tried my suggestion yet?

**Comment by frozenade** [comment]
My appologize, I didn't try yet. Soon after I re-install my laptop I'll inform you.
Thank you very much for your attention.

**Comment by adam-saudagar** [comment]
its been too long since you last commented, I'm closing this issue for now. Please feel free to create another issue or reopening this one if you are still facing it. :)
