### ISSUE TITLE
XPaths changed?

### ISSUE THREAD

**Issue by guifroes** [adsau59/supbot#8]
First of all, congratulations! This is an impressive project.

Following the tutorial video I managed to get as far as adding the chat group, with success. After that it didn't work for me. The bot did not respond to the `;;help` command or any other like in the tutorial.

Looking at the `XPaths` class values and inspecting `https://web.whatsapp.com/` page, I suspect that the page changed so the XPath values became obsolete.

Is it the case?

Thank you!

**Comment by adam-saudagar** [comment]
Yeh, whatsapp web has been updated alot since the last time I worked on the project, I'll have to update the Xpaths for it to work again

If u can, can you please update them and do a pull request?, if not I'll try to fix it in the next week, as I'm pretty busy atm.

**Comment by adam-saudagar** [comment]
Hi, @guifroes I have updated the xpaths, now the bot works perfectly. Thanks for letting me know. I am closing this issue, but if you find any other isssue, please feel free to create another one or reopen this one.
